### ISSUE TITLE
Update Assembly Version

### ISSUE THREAD

**Issue by PromoFaux** [ennerperez/CrystalDecisions#1]
Hi there,

Just wondering if you had any plans to update the assembly version of the DLLs in this project to 13.0.4000.0?

I have asked SAP about an official Nuget package, but they were more interested in trying to sell me Crystal Server :) I can try them again, but...

https://wiki.scn.sap.com/wiki/display/BOBJ/Crystal+Reports%2C+Developer+for+Visual+Studio+Downloads

Assembly version was upped to 4000 with SP26 of the runtime.

Cheers!

**Comment by ennerperez** [comment]
New version.
https://github.com/ennerperez/CrystalDecisions/releases/tag/v13.0.4000

**Comment by PromoFaux** [comment]
Thank you so very much!
