### ISSUE TITLE
Would it be possible to get a .NET Core (.NET 5) version of this?

### ISSUE THREAD

**Issue by rozeboosje** [ennerperez/CrystalDecisions#3]
When I install your nuGet package in my .NET 5 projects I get warnings like these:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'CrystalReports.Engine 13.0.4001' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.

**Comment by ennerperez** [comment]
Unfortunately, Crystal Reports doesn't support . NET Core
